language: java
os: linux
dist:
    - xenial


addons:
    apt:
        update: true
        packages:
            - repo
            - git
            - make
            - gcc-arm-none-eabi
            - binutils-arm-none-eabi
            - python-pip
            - python3-pip
            - python-pyscard
            - python-crypto
            - openjdk-8-jdk
            - maven
            - ant
            - curl
            - zip
            - unzip
            - bash

# installing dependencies
before_install:
    - pip install --user intelhex
    - sudo pip3 install kconfiglib
    - curl -o /tmp/gnat-community-2018-20180524-arm-elf-linux64-bin http://mirrors.cdn.adacore.com/art/5b0c1227a3f5d7097625478d
    - chmod +x /tmp/gnat-community-2018-20180524-arm-elf-linux64-bin
    - git clone https://github.com/AdaCore/gnat_community_install_script.git /tmp/gnat_install
    - /tmp/gnat_install/install_package.sh /tmp/gnat-community-2018-20180524-arm-elf-linux64-bin /opt/adacore-arm-eabi
    - curl -s "https://get.sdkman.io" -o /tmp/sdk
    - chmod +x /tmp/sdk
    - /tmp/sdk
    - sudo bash -c ". $HOME/.sdkman/bin/sdkman-init.sh && sdk install maven 3.6.1"
    - git clone https://github.com/martinpaljak/oracle_javacard_sdks.git /tmp/oracle_sdks

# let's sync and build for disco407, wookey, and build doc
jobs:
    include:
        - stage: javacard_build
          script:
              - mkdir build && cd build
              - export PATH=/opt/adacore-arm-eabi/bin:/usr/local/bin:$PATH
              - git config --global color.ui true
              - repo init -u https://github.com/wookey-project/manifest.git -m soft/wookey_nightly.xml && repo sync
              - echo 'export CROSS_COMPILE=arm-none-eabi-' > setenv.local.sh
              - echo 'export JAVA_SC_SDK=/tmp/oracle_sdks/jc303_kit' >> setenv.local.sh
              - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then cd javacard/applet && git fetch github refs/pull/${TRAVIS_PULL_REQUEST}/head && git checkout FETCH_HEAD; cd ../..; fi
              - source setenv.sh
              - make boards/wookey/configs/wookey2_graphic_ada_hs_defconfig
              - make prepare
              - make externals
              - make javacard_compile

notifications:
  email:
    recipients:
      - wookey@ssi.gouv.fr
    on_success: never
    on_failure: always
    on_pull_requests: always
